### PR TITLE
Feature/add env file

### PR DESCRIPTION
**Pull request by joeiannone**

### CODE REVIEW

**Comment by mcmoe** [comment]
Hello @joeiannone, what's the context that got you to use an env file?

**Comment by joeiannone** [comment]
Hey @mcmoe . I just wanted to be able to have various .env.{environment_name} files that contain respective database configuration and pass them in as needed when running docker-compose. Goal just being to keep environment specific configurations separate from the repo. I mostly have it setup how I wanted it on this master :[https://github.com/joeiannone/mssqldocker/tree/master](https://github.com/joeiannone/mssqldocker/tree/master).

Was really just intended for my own personal use. I didn't mean to PR onto your repo - Sorry for the bother 😭

**Comment by mcmoe** [comment]
No worries, glad you find it useful. If there is anything you believe would make sense to bake back into this repo please do let me know. Good luck.

**Comment by joeiannone** [comment]
@mcmoe Will keep that in mind. Thanks!

**Pull request closed without merging**
